# Numpy

1. Import the numpy package under the name np (★☆☆)
(hint:(**hint**: import … as …) 

In [1]:
import numpy as np

 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [5]:
print(np.__version__)

1.19.2


In [7]:
print(np.show_config)

<function show at 0x04B62F58>


 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [8]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [91]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
b = a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
a = np.arange(0,9)
b = a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [16]:
a = np.array([1,2,0,0,4,0])
b = np.nonzero(a)
b

(array([0, 1, 4], dtype=int32),)

In [94]:
a=np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int32),)

 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [17]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [18]:
a = np.random.random((3,3,3))
a

array([[[0.04108108, 0.74544337, 0.5679131 ],
        [0.98051509, 0.04158265, 0.29083488],
        [0.93786718, 0.4202377 , 0.07547919]],

       [[0.94480769, 0.41931795, 0.39852164],
        [0.98335433, 0.56011153, 0.40107325],
        [0.17568649, 0.94396283, 0.04441884]],

       [[0.8433337 , 0.41144019, 0.78533911],
        [0.57207442, 0.97743106, 0.47066537],
        [0.01383336, 0.06603084, 0.16106572]]])

 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [19]:
a = np.random.random((10,10))
print("minimum", a.min())
print("maximum", a.max())

minimum 0.003251125909453867
maximum 0.9819917019079091


14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [20]:
a = np.random.random(30)
a.mean()

0.46728575054215465

 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [97]:
Z = np.ones((5,5),dtype=int)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [101]:
Z = np.ones((5,5),dtype=int)
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
print('--------------------------------------')
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
--------------------------------------
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [24]:
x=np.array([[2,3,4],[5,6,7],[1,8,9]])
y = np.pad(x, pad_width=1)
y

array([[0, 0, 0, 0, 0],
       [0, 2, 3, 4, 0],
       [0, 5, 6, 7, 0],
       [0, 1, 8, 9, 0],
       [0, 0, 0, 0, 0]])

 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 

(**hint**: np.diag)

In [102]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
v = np.array([1,2,3,4])
b = np.diag(v, k = -1)
b

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [41]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [90]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [87]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [3]:
a= np.random.random((5,5))
print(a)
print('------------------------------------------')
amax = a.max()
amin = a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

[[0.53188881 0.96550493 0.59317744 0.38313944 0.72295195]
 [0.41077926 0.33551028 0.78599762 0.95965269 0.2137718 ]
 [0.89884807 0.89547904 0.23375617 0.62088005 0.85880411]
 [0.00472157 0.89038769 0.8132693  0.99673053 0.55243232]
 [0.02505852 0.1433281  0.91253194 0.91357866 0.99719334]]
------------------------------------------
After normalization:
[[0.53116598 0.96807122 0.5929195  0.3812883  0.7236784 ]
 [0.40913777 0.33329786 0.78720229 0.96217459 0.21063594]
 [0.90090875 0.89751416 0.2307719  0.62083224 0.86056104]
 [0.         0.89238419 0.81468083 0.99953367 0.55186531]
 [0.02049121 0.1396579  0.91469642 0.91575107 1.        ]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [106]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [73]:
a=np.array([[10,20,30],[40,50,60],[70,80,90],[15,25,35],[45,55,65]])
b=np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(b.shape)
print("--------------------------")
c=a.dot(b)
print(c)

(5, 3)
(3, 2)
--------------------------
[[ 220  280]
 [ 490  640]
 [ 760 1000]
 [ 265  340]
 [ 535  700]]


In [107]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [108]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)

In [15]:
print('Before import numpy')
a=range(5) # 0,1,2,3,4
print(sum(a)) # (0+1+2+3+4)
print(sum(a)-1) # (0+1+2+3+4+(-1) =9)
print('After import numpy')

from numpy import *
b=range(5) # 0,1,2,3,4
print(sum(b)) # 10
sum(b)-1 # (0+1+2+3+4,xaxis=-1 ,0+1+2+3+4 on axis=-1)
# actually doing is:
#print(np.sum(b,axis=-1)) # ans:10
print(sum(range(5),-1))


Before import numpy
10
9
After import numpy
10
10


In [109]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [36]:
Z**Z



array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [112]:
2 << Z >> 2

array([  0,   1,   2,   4,   0,   0,   0,   0, 128, 256, 512], dtype=int32)

In [113]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False])

In [114]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j,  0. +8.j,  0. +9.j,  0.+10.j])

In [115]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10.])

In [37]:
Z = np.array([1,2,3])
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [38]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-26-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-26-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
#1.copysign-copy the sign,
#2.ceil-(-ve)-lowerbound value,(+ve)-upperbound
#3.floor-opposite to ceil

In [27]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.copysign(np.ceil(np.abs(a)), a))
                                         
# More readable but less efficient       
print(np.where(a>0, np.ceil(a), np.floor(a)))

[-3.18900868  1.95999702 -3.99369807 -4.81631947  5.250241    4.2885733
 -7.64916503 -4.68496039  1.19752276  1.68171852]
[-4.  2. -4. -5.  6.  5. -8. -5.  2.  2.]
[-4.  2. -4. -5.  6.  5. -8. -5.  2.  2.]


In [31]:
#practice 
a = np.random.uniform(-10,+10,10)
print(a)
print("*********************************************")
b=np.abs(a)
print(b)
print("----------------------------------------------")
c=np.ceil(b)
print(c)
print('----------------------------------------------')
d=np.copysign(c,a)
print(d)


[ 5.90842269  5.71865523  2.99812072  1.84342325  7.31712648  8.38858724
 -7.08907646 -1.92996105 -8.34996867 -8.5661376 ]
*********************************************
[5.90842269 5.71865523 2.99812072 1.84342325 7.31712648 8.38858724
 7.08907646 1.92996105 8.34996867 8.5661376 ]
----------------------------------------------
[6. 6. 3. 2. 8. 9. 8. 2. 9. 9.]
----------------------------------------------
[ 6.  6.  3.  2.  8.  9. -8. -2. -9. -9.]


 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [32]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[8 9 5 0 7 2 8 1 7 6]
[8 3 3 2 2 8 9 5 0 1]
[0 1 2 5 8 9]


In [34]:
z1=np.array([[1,2],[3,4]])
z2=np.array([[2,3],[1,6]])
print(np.intersect1d(z1,z2))

[1 2 3]


31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

Reference:

#numpy.seterr(all=None, divide=None, over=None, under=None, invalid=None)
                      -------------------
Set how floating-point errors are handled.

Note that operations on integer scalar types (such as int16) are handled like floating point, and are affected by these settings.
                       ------------------
Parameters
all{‘ignore’, ‘warn’, ‘raise’, ‘call’, ‘print’, ‘log’}, optional

Set treatment for all types of floating-point errors at once:

ignore: Take no action when the exception occurs.

warn: Print a RuntimeWarning (via the Python warnings module).

raise: Raise a FloatingPointError.

call: Call a function specified using the seterrcall function.

print: Print a warning directly to stdout.

log: Record error in a Log object specified by seterrcall.

The default is not to change the current behavior.

In [42]:
#practice:
a = np.ones(1)
print(a)


[1.]


In [44]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
print(Z.dtype)

# Back to sanity
_ = np.seterr(**defaults)
print(_)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    b=np.arange(3) / 0
    print(b)

[inf]
float64
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
[nan inf inf]


 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#numpy.emath alias numpy.lib.scimath (available after numpy is imported.)
#Compute the square root of x.

For negative input elements, a complex value is returned (unlike numpy.sqrt which returns NaN).

In [50]:
np.sqrt(-1)

nan

In [51]:
np.emath.sqrt(-1)

1j

In [122]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [39]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-08-11
2021-08-12
2021-08-13


 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [52]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [53]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [4]:
Z = np.random.uniform(0,10,10)
print(Z)
print('---------------------------')
print(Z%1)
print('---------------------------')

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8.8591227  4.7449256  1.54418293 4.60938298 8.49121778 1.65828114
 8.32162979 0.20175041 4.68671709 2.58117243]
---------------------------
[0.8591227  0.7449256  0.54418293 0.60938298 0.49121778 0.65828114
 0.32162979 0.20175041 0.68671709 0.58117243]
---------------------------
[8. 4. 1. 4. 8. 1. 8. 0. 4. 2.]
[8. 4. 1. 4. 8. 1. 8. 0. 4. 2.]
[8. 4. 1. 4. 8. 1. 8. 0. 4. 2.]
[8 4 1 4 8 1 8 0 4 2]
[8. 4. 1. 4. 8. 1. 8. 0. 4. 2.]


 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [7]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
print("-------------------------------------")

z= np.ones((5,5))
z *= np.arange(5)
print(z)
print("-------------------------------------")

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
-------------------------------------
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
-------------------------------------
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [56]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [11]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [58]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04807897 0.05742287 0.1461608  0.16926212 0.18031565 0.38945543
 0.41164114 0.43934787 0.71179737 0.83771872]


 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [59]:
Z = np.arange(10)
np.add.reduce(Z)

45

 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [61]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

[0 0 1 1 0]
[0 1 0 1 1]


In [62]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [63]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [64]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.35187429 0.40931978 0.59468539 1.15095059 0.83114109 0.91817073
 0.95867602 0.8613693  0.75032547 1.12023397]
[0.69564288 1.0642239  0.15008444 0.81021375 0.53020039 0.09364163
 0.3761055  1.13150772 0.7460401  0.63511404]


 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [65]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.44315229 0.67431617 0.08699026 0.         0.00227193 0.10787864
 0.85047514 0.6317422  0.83614186 0.03698697]


 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [66]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [67]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [68]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [69]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [70]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

87


 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [72]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-72-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [73]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.05608674 0.69375751 0.67358473 0.84578629 0.91990822
  0.63090301 0.63389338 0.14727116 0.86049347]
 [0.05608674 0.         0.67408779 0.65306997 0.79904644 0.8661497
  0.59704187 0.58262065 0.13483842 0.80644287]
 [0.69375751 0.67408779 0.         0.02330085 0.48263071 0.7267406
  0.19978985 0.50492467 0.80233363 0.70121916]
 [0.67358473 0.65306997 0.02330085 0.         0.47161118 0.71235186
  0.18096057 0.4853084  0.78076251 0.6854261 ]
 [0.84578629 0.79904644 0.48263071 0.47161118 0.         0.26273902
  0.31658613 0.2449513  0.88028604 0.26013977]
 [0.91990822 0.8661497  0.7267406  0.71235186 0.26273902 0.
  0.53894696 0.3000216  0.91196059 0.06174427]
 [0.63090301 0.59704187 0.19978985 0.18096057 0.31658613 0.53894696
  0.         0.30536343 0.71010538 0.50806355]
 [0.63389338 0.58262065 0.50492467 0.4853084  0.2449513  0.3000216
  0.30536343 0.         0.64855374 0.24831161]
 [0.14727116 0.13483842 0.80233363 0.78076251 0.88028604 0.91196059
  0.71010538 0.64855374

 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [74]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[44 65 83 31 66 29 54 71 29 59]


54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [75]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [76]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [77]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [78]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [79]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.14553393 -0.05261199  0.20927141  0.10542101 -0.41029254  0.47279211
   0.02512908 -0.08234356 -0.09238719 -0.0294444 ]
 [ 0.06328947  0.40110152 -0.27478064 -0.09770256 -0.1654745  -0.3066573
   0.14951554 -0.08262192 -0.11409042  0.42742081]
 [ 0.28214666  0.22626314  0.0591209  -0.6597127   0.32797327  0.20489224
  -0.64718493  0.28983799  0.03643135 -0.1197679 ]
 [-0.31812521  0.34324908 -0.11052071  0.14567093  0.09229729 -0.09306341
  -0.31829185  0.34611612  0.14989604 -0.23722829]
 [ 0.00144933 -0.30290682  0.02739419 -0.08920858  0.16122286 -0.19188941
  -0.31868716 -0.39220657  0.57748255  0.52734961]]


 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [80]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 2 4]
 [8 4 3]
 [4 8 7]]
[[7 2 4]
 [8 4 3]
 [4 8 7]]


 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [81]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [82]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4856289537715216


 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [83]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [84]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [85]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[1. 1. 4. 2. 2. 4. 4. 3. 5. 4.]
[1. 1. 7. 3. 3. 7. 7. 5. 9. 7.]


 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [86]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [87]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
hint: sum(axis=(-2,-1))

In [89]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 58 53 67]
 [45 69 44 53]
 [50 54 45 66]]
[[49 58 53 67]
 [45 69 44 53]
 [50 54 45 66]]


 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [88]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.65114048 0.40800282 0.52758667 0.36976892 0.54775421 0.67838613
 0.492952   0.50064836 0.47444525 0.41546043]
0    0.651140
1    0.408003
2    0.527587
3    0.369769
4    0.547754
5    0.678386
6    0.492952
7    0.500648
8    0.474445
9    0.415460
dtype: float64


 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [90]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.18182058, 1.69845583, 1.71925199, 1.46643639, 0.79163611])

 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [91]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [3]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [5]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3,  5) ( 3,  7) ( 5,  7) ( 7, 13) ( 7, 27) ( 7, 44) ( 7, 55) (13, 55)
 (27, 44) (32, 41) (32, 72) (32, 79) (32, 99) (33, 38) (33, 40) (34, 34)
 (34, 36) (38, 40) (38, 77) (38, 93) (41, 72) (49, 52) (49, 72) (52, 72)
 (62, 66) (62, 74) (66, 74) (77, 93) (79, 99)]


 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [6]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [7]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [8]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [9]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.79592522,  0.51739032, -0.5497353 ,  0.82135092, -0.20270021,
       -0.98123023,  0.88042778,  0.25062249, -0.38063494, -0.08455157,
       -0.19360344, -0.46453848, -0.10008628,  0.22969734,  0.7117364 ,
       -0.74829969,  0.47585077,  0.60506743, -0.96256407,  0.04390182,
        0.4915929 , -0.90610719, -0.15216851,  0.27436088, -0.61702509,
        0.23948548, -0.77843229,  0.91267453, -0.35339834, -0.10320956,
       -0.52704773,  0.7787686 ,  0.90378557, -0.70196325,  0.62586829,
        0.81914759, -0.36383972, -0.82247855, -0.57180163, -0.93954398,
        0.69751023, -0.03808077,  0.50162145, -0.85880642,  0.54604117,
        0.81365847,  0.15632512, -0.57368298,  0.51425211,  0.14648646,
       -0.25241223,  0.6659165 ,  0.3898068 , -0.60228738,  0.80435665,
       -0.29254741,  0.4537787 ,  0.35419281,  0.65964624, -0.43104884,
        0.81426938,  0.60420625,  0.31804218,  0.57698605,  0.71060785,
       -0.49576773,  0.77262009,  0.22752813, -0.96057572, -0.73

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [10]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.59233456  0.82489066  0.57285655  7.99843932 11.28593926  3.16165283
  4.83538932  5.54624522  2.53594602  7.25328857]


 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [11]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.5742118  16.6814623   4.25459602  5.70927925 10.53569928 12.99911659
   1.21325512  3.18858795  7.17123699  2.67505329]
 [ 7.10673631  2.93610385  4.12427214  9.73634275  0.10203922  3.97769273
   0.89989668  6.43747201  5.51614426 10.53182871]
 [13.70421452 17.31269933  6.46579636  2.51921936  6.58573984 10.82015918
   2.56808985  0.8088676   3.42879108  6.70323486]
 [ 0.62254578  6.68548729  6.40667928  4.22937323 13.90053493  8.05274199
   9.37656268  7.29173346 15.5177568   2.58839302]
 [ 6.138334    8.3897943   2.24101289  0.53111235  7.62098434  5.09270357
   2.99889995  0.88496954  9.18590511  3.95124824]
 [ 6.55695323  6.8403285   2.68785894  3.33477439  5.21239903  2.37278813
   1.70387994  1.40985516  7.95885196  6.03286003]
 [ 5.47147954  1.04529159  5.98896931 10.34071487  0.16515257  5.15949752
   0.3215625   6.03070969  6.7772461   9.90138307]
 [13.11698662 14.67905492  4.90781547  0.54146421  4.43225835  7.49052797
   3.0736943   2.76853591  3.01250834  8.32259179]


 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [12]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 3 0 7 9 7 6 3 5 7]
 [4 5 5 1 4 3 1 5 5 2]
 [2 9 0 2 2 5 4 0 4 5]
 [8 4 4 9 2 0 5 9 6 0]
 [5 2 3 3 3 6 6 8 6 1]
 [4 2 2 7 1 5 3 3 2 4]
 [4 3 6 2 2 0 2 8 1 0]
 [8 8 4 7 2 1 9 9 1 6]
 [3 1 4 8 0 1 5 4 6 4]
 [6 7 8 2 2 5 2 3 9 8]]
[[0 0 0 0 0]
 [0 2 3 0 7]
 [0 4 5 5 1]
 [0 2 9 0 2]
 [0 8 4 4 9]]


<ipython-input-12-69265b202653>:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [13]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [14]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [15]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [16]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 3 1]
   [4 0 0]
   [2 1 3]]

  [[3 1 0]
   [0 0 4]
   [1 3 0]]

  [[1 0 2]
   [0 4 1]
   [3 0 1]]

  [[0 2 3]
   [4 1 4]
   [0 1 4]]

  [[2 3 2]
   [1 4 0]
   [1 4 2]]

  [[3 2 1]
   [4 0 0]
   [4 2 3]]

  [[2 1 3]
   [0 0 0]
   [2 3 3]]

  [[1 3 0]
   [0 0 2]
   [3 3 4]]]


 [[[4 0 0]
   [2 1 3]
   [2 2 4]]

  [[0 0 4]
   [1 3 0]
   [2 4 4]]

  [[0 4 1]
   [3 0 1]
   [4 4 3]]

  [[4 1 4]
   [0 1 4]
   [4 3 4]]

  [[1 4 0]
   [1 4 2]
   [3 4 0]]

  [[4 0 0]
   [4 2 3]
   [4 0 3]]

  [[0 0 0]
   [2 3 3]
   [0 3 0]]

  [[0 0 2]
   [3 3 4]
   [3 0 3]]]


 [[[2 1 3]
   [2 2 4]
   [2 4 2]]

  [[1 3 0]
   [2 4 4]
   [4 2 1]]

  [[3 0 1]
   [4 4 3]
   [2 1 2]]

  [[0 1 4]
   [4 3 4]
   [1 2 4]]

  [[1 4 2]
   [3 4 0]
   [2 4 0]]

  [[4 2 3]
   [4 0 3]
   [4 0 0]]

  [[2 3 3]
   [0 3 0]
   [0 0 2]]

  [[3 3 4]
   [3 0 3]
   [0 2 2]]]


 [[[2 2 4]
   [2 4 2]
   [4 2 4]]

  [[2 4 4]
   [4 2 1]
   [2 4 1]]

  [[4 4 3]
   [2 1 2]
   [4 1 4]]

  [[4 3 4]
   [1 2 4]
   [1 4 3]]

  [[3 4 0]
   

 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [17]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 11  9 11 13]
 [11  1  1 11 13]
 [ 9  1  1 42 17]
 [11 11 42  9  8]
 [13 13 17  8  0]]


 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [18]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [19]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


AttributeError: module 'numpy.lib.stride_tricks' has no attribute 'sliding_window_view'

 88. How to implement the Game of Life using numpy arrays? (★★★)

In [20]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [21]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [22]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [23]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [25]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

SyntaxError: invalid syntax (<ipython-input-25-a0dd1ce11e58>, line 3)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [26]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 7]


 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [27]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 3]
 [2 0 3]
 [4 3 3]
 [4 2 1]
 [2 0 0]
 [0 2 0]
 [2 1 3]
 [2 2 0]
 [4 2 1]
 [3 0 4]]
[[2 4 3]
 [2 0 3]
 [4 3 3]
 [4 2 1]
 [2 0 0]
 [0 2 0]
 [2 1 3]
 [2 2 0]
 [4 2 1]
 [3 0 4]]
[[2 4 3]
 [2 0 3]
 [4 3 3]
 [4 2 1]
 [2 0 0]
 [0 2 0]
 [2 1 3]
 [2 2 0]
 [4 2 1]
 [3 0 4]]


 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [28]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [29]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [30]:
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.626713  , 0.45095694, 0.16815771, 0.74321656, 0.61126728,
        0.45726351, 0.52519711, 0.29567814, 0.49677995, 0.57365539],
       [0.20907079, 0.15043875, 0.05609723, 0.24793625, 0.20391811,
        0.15254262, 0.17520519, 0.09863791, 0.16572526, 0.19137082],
       [0.70770689, 0.50923681, 0.18988974, 0.8392669 , 0.69026502,
        0.51635842, 0.59307149, 0.3338904 , 0.56098181, 0.64779232],
       [0.27415379, 0.19726981, 0.0735601 , 0.32511793, 0.2673971 ,
        0.2000286 , 0.22974595, 0.12934354, 0.21731495, 0.25094389],
       [0.2919689 , 0.21008883, 0.0783402 , 0.34624481, 0.28477315,
        0.2130269 , 0.24467535, 0.13774857, 0.23143655, 0.26725077],
       [0.41911093, 0.30157501, 0.11245456, 0.49702205, 0.40878169,
        0.3057925 , 0.35122273, 0.19773315, 0.33221891, 0.38362894],
       [0.47593276, 0.34246167, 0.12770082, 0.56440685, 0.46420311,
        0.34725095, 0.39884047, 0.22454124, 0.37726017, 0.43564023],
       [0.00901376, 0.00648593, 0.0024185

 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [32]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [33]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [34]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.08120371  0.28659475]
